security:

    encoders:
        App\Entity\Enseignant:
            algorithm: bcrypt
        App\Entity\Eleve:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }

        chain_provider:
            chain:
                providers: [app_student_provider, app_teacher_provider, app_admin_provider]
        app_student_provider:
            entity:
                class: App\Entity\Eleve
                property: email
        app_teacher_provider:
            entity:
                class: App\Entity\Enseignant
                property: email
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:

            pattern: ^/

            anonymous : lazy 

            provider: chain_provider

            form_login: 
                login_path: login
                check_path: redirection
            
            logout:
                path: app_logout

    access_control:
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/professeur, roles: ROLE_USER }
          - { path: ^/eleve, roles: ROLE_USER_ELEVE }
